from __future__ import annotations

import argparse
from pathlib import Path
from pprint import pformat
import re


def _sections(path: Path) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    current: dict[str, str] | None = None
    current_id = ""
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        line = raw_line.strip()
        match = re.fullmatch(r"\[([^]]+)]", line)
        if match:
            current_id = match.group(1).upper()
            current = result.setdefault(current_id, {})
        elif current is not None and "=" in line and not line.startswith("#"):
            key, value = line.split("=", 1)
            current[key.strip()] = value.strip()
    return result


def _ability_names(path: Path) -> dict[str, str]:
    names: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8-sig").splitlines():
        if "," not in raw_line:
            continue
        token, name = raw_line.split(",", 1)
        names[token.strip().upper()] = name.strip()
    return names


def _enum_token(name: str) -> str:
    return "".join(char for char in name if char.isalnum())


def build(pokemon_path: Path, ability_path: Path, catalog_path: Path) -> dict[str, object]:
    sections = _sections(pokemon_path)
    ability_names = _ability_names(ability_path)
    catalog_source = catalog_path.read_text(encoding="utf-8")
    manifest = re.search(r'_SPECIES_MANIFEST = """(.*?)"""', catalog_source, re.DOTALL)
    if manifest is None:
        raise ValueError("Could not find _SPECIES_MANIFEST in catalog.py")
    species_names = [line.split("|", 1)[0] for line in manifest.group(1).strip().splitlines()]
    aliases = {"VENASAUR": "VENUSAUR"}
    result: dict[str, object] = {}
    for species_name in species_names:
        key = aliases.get(species_name.upper(), species_name.upper().replace(".", ""))
        record = sections.get(key)
        if record is None:
            continue
        raw_stats = [int(value) for value in record["BaseStats"].split(",")]
        if len(raw_stats) != 6:
            raise ValueError(f"Unexpected BaseStats for {species_name}")
        abilities: list[dict[str, object]] = []
        for slot, token in enumerate(filter(None, record.get("Abilities", "").split(","))):
            token = token.strip().upper()
            name = ability_names.get(token, token.title())
            abilities.append({"name": name, "enum": _enum_token(name), "slot": slot, "hidden": False})
        for token in filter(None, record.get("HiddenAbilities", "").split(",")):
            token = token.strip().upper()
            name = ability_names.get(token, token.title())
            abilities.append({"name": name, "enum": _enum_token(name), "slot": 2, "hidden": True})
        result[species_name] = {
            "types": [value.strip().title() for value in record["Types"].split(",")],
            "base_stats": {
                "HP": raw_stats[0],
                "Attack": raw_stats[1],
                "Defense": raw_stats[2],
                "Speed": raw_stats[3],
                "SpecialAttack": raw_stats[4],
                "SpecialDefense": raw_stats[5],
            },
            "abilities": abilities,
            "height_m": float(record.get("Height", 0)),
            "weight_kg": float(record.get("Weight", 0)),
        }
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the source-only Gamma species metadata module.")
    parser.add_argument("--pokemon", type=Path, required=True)
    parser.add_argument("--abilities", type=Path, required=True)
    parser.add_argument(
        "--catalog", type=Path,
        default=Path(__file__).resolve().parents[1] / "src" / "gamma_editor" / "catalog.py",
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    data = build(args.pokemon, args.abilities, args.catalog)
    payload = pformat(data, sort_dicts=True, width=110)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "# Generated by scripts/build_species_metadata.py; do not edit by hand.\n"
        "from __future__ import annotations\n\n"
        f"SPECIES_METADATA_RAW = {payload}\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(data)} species to {args.output}")


if __name__ == "__main__":
    main()
