#!/usr/bin/env python3
"""Generate the GE-1.0.0 species move catalog from UAssetAPI JSON exports.

The encrypted game assets and their JSON exports are analysis inputs only.  The generated module
contains move names/levels, never game payloads, save data, encryption keys, or copyrighted assets.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import struct
from pathlib import Path


# GE-1.0.0 has explicit shipped HM UI/dialogue assets for these moves.  Species compatibility is
# still read from each species' LearnableTMMoves property; this set only splits that exact machine
# list into TM and HM labels.
HM_MOVE_TOKENS = frozenset({"Cut", "Fly", "RockSmash", "Strength", "Surf"})


def _move_at(raw: bytes, names: list[str], offset: int) -> str | None:
    path_index, path_number, class_index, class_number, subpath_size = struct.unpack_from(
        "<IIIII", raw, offset
    )
    if path_number or class_number or subpath_size:
        return None
    if path_index >= len(names) or class_index >= len(names):
        return None
    path_match = re.search(r"/BP_Move_(.+)$", names[path_index])
    class_match = re.fullmatch(r"BP_Move_(.+)_C", names[class_index])
    if not path_match or not class_match or path_match.group(1) != class_match.group(1):
        return None
    return path_match.group(1)


def _array_candidates(
    raw: bytes,
    names: list[str],
    end: int,
    *,
    entry_size: int,
    level_up: bool = False,
) -> list[tuple[int, tuple]]:
    candidates: list[tuple[int, tuple]] = []
    for count in range(201):
        start = end - 4 - count * entry_size
        if start < 0 or struct.unpack_from("<I", raw, start)[0] != count:
            continue
        entries: list[object] = []
        valid = True
        for index in range(count):
            entry = start + 4 + index * entry_size
            move_offset = entry
            if level_up:
                # Each nested PokemonLevelUpMoves struct has a two-byte unversioned header.
                if raw[entry : entry + 2] != b"\x00\x05":
                    valid = False
                    break
                move_offset += 2
            move = _move_at(raw, names, move_offset)
            if move is None:
                valid = False
                break
            entries.append(
                (struct.unpack_from("<I", raw, move_offset + 20)[0], move) if level_up else move
            )
        if valid:
            candidates.append((start, tuple(entries)))
    return candidates


def _longest(candidates: list[tuple[int, tuple]]) -> tuple[int, tuple] | None:
    return max(candidates, key=lambda candidate: len(candidate[1]), default=None)


def parse_species_export(path: Path) -> tuple[str, dict[str, tuple]]:
    document = json.loads(path.read_text(encoding="utf-8"))
    names = document["NameMap"]
    raw = base64.b64decode(document["Exports"][0]["Data"])
    if raw[-4:] != b"\0\0\0\0":
        raise ValueError(f"{path.name}: unexpected UObject trailer")

    machine_candidates = [
        candidate
        for candidate in _array_candidates(raw, names, len(raw) - 4, entry_size=20)
        if candidate[1]
    ]
    if len(machine_candidates) > 1:
        raise ValueError(f"{path.name}: ambiguous LearnableTMMoves array")
    machine_start, machine_moves = machine_candidates[0] if machine_candidates else (len(raw) - 4, ())

    level_result = _longest(
        _array_candidates(raw, names, machine_start, entry_size=26, level_up=True)
    )
    if level_result is None:
        raise ValueError(f"{path.name}: PokemonLevelUpMoves array not found")
    level_start, level_moves = level_result
    if any(not 0 <= level <= 100 for level, _move in level_moves):
        raise ValueError(f"{path.name}: invalid learn level")

    egg_result = _longest(_array_candidates(raw, names, level_start, entry_size=20))
    egg_moves = egg_result[1] if egg_result else ()
    species = path.name.removeprefix("DA_").removesuffix(".uasset.json")
    return species, {
        "level_up": level_moves,
        "egg": egg_moves,
        "tm": tuple(move for move in machine_moves if move not in HM_MOVE_TOKENS),
        "hm": tuple(move for move in machine_moves if move in HM_MOVE_TOKENS),
    }


def render_module(learnsets: dict[str, dict[str, tuple]]) -> str:
    lines = [
        '"""Generated exact move learnsets from the shipped Gamma Emerald GE-1.0.0 DataAssets."""',
        "",
        "from __future__ import annotations",
        "",
        "# Generated by scripts/build_move_learnsets.py. Do not edit by hand.",
        "MOVE_LEARNSETS_RAW: dict[str, dict[str, tuple]] = {",
    ]
    for species in sorted(learnsets, key=str.casefold):
        sources = learnsets[species]
        lines.append(f"    {species!r}: {{")
        for source in ("level_up", "tm", "hm", "egg"):
            lines.append(f"        {source!r}: {sources[source]!r},")
        lines.append("    },")
    lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_dir", type=Path, help="Directory containing UAssetAPI species JSON exports")
    parser.add_argument("output", type=Path, help="Generated Python module")
    args = parser.parse_args()

    learnsets: dict[str, dict[str, tuple]] = {}
    for path in sorted(args.input_dir.rglob("DA_*.uasset.json")):
        species, sources = parse_species_export(path)
        if species in learnsets:
            raise ValueError(f"duplicate species {species}")
        learnsets[species] = sources
    if not learnsets:
        raise ValueError("no DA_*.uasset.json exports found")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_module(learnsets), encoding="utf-8", newline="\n")
    print(f"Generated {len(learnsets)} exact species learnsets -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
