#!/usr/bin/env python3
"""Generate GE-1.0.0 move Base PP from local UAssetAPI JSON exports.

Most move Blueprints serialize CurrentPP and MaxPP as an identical adjacent int pair in their
class-default object.  A small set inherits one or both values from the game's parent Blueprint;
those verified inherited values are listed explicitly below.  Generated output contains numbers
and move tokens only, never game payloads, encryption keys, save data, or asset files.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import struct
from pathlib import Path


INHERITED_BASE_PP = {
    "Bide": 10,
    "BlazeKick": 10,
    "BulkUp": 20,
    "Earthquake": 10,
    "IceBeam": 10,
    "KarateChop": 25,
    "LeafStorm": 5,
    "MeteorMash": 10,
    "Mudslap": 10,
    "Protect": 10,
    "Psychic": 10,
    "Refresh": 20,
    "Revenge": 10,
    "RockSlide": 10,
    "Struggle": 1,
    "Supersonic": 20,
    "Toxic": 10,
    "VitalThrow": 10,
}


def parse_move_export(path: Path) -> tuple[str, int]:
    token = path.name.removeprefix("BP_Move_").removesuffix(".uasset.json")
    document = json.loads(path.read_text(encoding="utf-8"))
    object_name = f"Default__BP_Move_{token}_C"
    try:
        encoded = next(item["Data"] for item in document["Exports"] if item["ObjectName"] == object_name)
    except StopIteration as exc:
        raise ValueError(f"{path.name}: class-default object not found") from exc
    raw = base64.b64decode(encoded)
    candidates: list[int] = []
    for offset in range(max(0, len(raw) - 7)):
        current, maximum = struct.unpack_from("<II", raw, offset)
        if current == maximum and 1 <= current <= 64:
            candidates.append(current)
    if candidates:
        return token, candidates[-1]
    try:
        return token, INHERITED_BASE_PP[token]
    except KeyError as exc:
        raise ValueError(f"{path.name}: Base PP pair not found and no inherited value is mapped") from exc


def render_module(values: dict[str, int]) -> str:
    lines = [
        '"""Generated GE-1.0.0 Base PP values for the editor move catalog."""',
        "",
        "from __future__ import annotations",
        "",
        "# Generated by scripts/build_move_pp.py. Do not edit by hand.",
        "MOVE_BASE_PP_RAW: dict[str, int] = {",
    ]
    lines.extend(f"    {token!r}: {values[token]}," for token in sorted(values, key=str.casefold))
    lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_dir", type=Path, help="Directory containing UAssetAPI move JSON exports")
    parser.add_argument("output", type=Path, help="Generated Python module")
    args = parser.parse_args()

    values: dict[str, int] = {}
    for path in sorted(args.input_dir.rglob("BP_Move_*.uasset.json")):
        token, base_pp = parse_move_export(path)
        if token in values:
            raise ValueError(f"duplicate move {token}")
        values[token] = base_pp
    if len(values) != 99:
        raise ValueError(f"expected 99 GE-1.0.0 moves, found {len(values)}")
    if set(INHERITED_BASE_PP) - set(values):
        raise ValueError("one or more inherited Base PP entries are absent from the move catalog")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_module(values), encoding="utf-8", newline="\n")
    print(f"Generated {len(values)} exact move Base PP values -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
